### ISSUE TITLE
Standalone SO sea ice area compared to obs

### ISSUE THREAD

**Issue by PaulSpence** [dpath2o/AFIM#1]
Plot of SIA monthly time-series, or seasonal averages. Some other diagnostic examples here: 
https://github.com/COSIMA/cosima-recipes/blob/main/DocumentedExamples/SeaIceSeasonality_DFA.ipynb

**Comment by PaulSpence** [comment]
Compare obs to om2 and the standalone model. What is an acceptable bias?
![Uploading Screen Shot 2023-10-09 at 1.18.53 pm.png…]()

**Comment by willrhobbs** [comment]
I have a repo on OM2-NSIDC validation [here](https://github.com/willrhobbs/OM2_VALIDATION/blob/main/OM2_obs_sic_comparison_map.ipynbl)

**Comment by dpath2o** [comment]
@willrhobbs , I got a "404" error when I click on the link ( https://github.com/willrhobbs/OM2_VALIDATION/blob/main/OM2_obs_sic_comparison_map.ipynbl ) you provided ... ah, maybe it's because it has an extra "l" there at the end ... nope, that did not solve it ... and I don't see it as part of your repositories in: https://github.com/willrhobbs

**Comment by PaulSpence** [comment]
Understand that Dan is moving from using JRA to ERA5 as forcing. Will compare this standalone sea ice area ERA5 output to obs and access-om2.

See example plot here:

https://github.com/dpath2o/AFIM/issues/3#issuecomment-1752397697

**Comment by dpath2o** [comment]
this issue is closed, see for further information http://131.217.175.138/~ec2-user/research/cice6_standalone.html
